 
name: psa
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - lxml
  - astropy
  - astroquery
  - pyvo
  - numpy
  - pandas
  - matplotlib
  - pyyaml
  - requests
  - prettytable
  - pip
  - pip:
    - pds4_utils
